apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  labels:
    app: redis
data: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        imagePullPolicy: IfNotPresent
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
        ports:
        - name: redis
          containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 56379
    protocol: TCP
    targetPort: redis
  type: ClusterIP