apiVersion: v1
kind: ConfigMap
metadata:
  name: client-cm
  labels:
    app: client
data: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 6
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: grpc
        image: umi0410/streaming-chat
        imagePullPolicy: Always
        args:
          - "--randomUsername"
          - "--sendRandomChatMessage"
          - "-serverAddr"
          - "server:55555"
          - "client"
        env: []

