apiVersion: v1
kind: ConfigMap
metadata:
  name: server-cm
  labels:
    app: server
data: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: grpc
        image: umi0410/streaming-chat
        imagePullPolicy: Always
        args:
          - "-redisAddr"
          - "redis:56379"
          - "-serverAddr"
          - "0.0.0.0:55555"
          - "server"
        env: []
        ports:
        - name: grpc
          containerPort: 55555

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  selector:
    app: server
  ports:
  - name: grpc
    port: 55555
    protocol: TCP
    targetPort: grpc
  type: ClusterIP
