apiVersion: v1
kind: ConfigMap
metadata:
  name: straming-chat-server-cm
  labels:
    app: straming-chat-server
data: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: straming-chat-server
  labels:
    app: straming-chat-server
spec:
  replicas: 5
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: straming-chat-server
  template:
    metadata:
      labels:
        app: straming-chat-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gRPC
        image: umi0410/streamingChat
        imagePullPolicy: Always
        args: ["server", "--redisAddr", "redis:50051"]
        env: []
        ports:
        - name: gRPC
          containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: straming-chat-server
  name: straming-chat-server
spec:
  selector:
    app: straming-chat-server
  ports:
  - name: gRPC
    port: 55555
    protocol: TCP
    targetPort: straming-chat-server
  type: ClusterIP
