// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pb/chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*ChatStream_Login_
	//	*ChatStream_Logout_
	//	*ChatStream_Message_
	Event isChatStream_Event `protobuf_oneof:"Event"`
}

func (x *ChatStream) Reset() {
	*x = ChatStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStream) ProtoMessage() {}

func (x *ChatStream) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStream.ProtoReflect.Descriptor instead.
func (*ChatStream) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{0}
}

func (m *ChatStream) GetEvent() isChatStream_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ChatStream) GetLogin() *ChatStream_Login {
	if x, ok := x.GetEvent().(*ChatStream_Login_); ok {
		return x.Login
	}
	return nil
}

func (x *ChatStream) GetLogout() *ChatStream_Logout {
	if x, ok := x.GetEvent().(*ChatStream_Logout_); ok {
		return x.Logout
	}
	return nil
}

func (x *ChatStream) GetMessage() *ChatStream_Message {
	if x, ok := x.GetEvent().(*ChatStream_Message_); ok {
		return x.Message
	}
	return nil
}

type isChatStream_Event interface {
	isChatStream_Event()
}

type ChatStream_Login_ struct {
	Login *ChatStream_Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type ChatStream_Logout_ struct {
	Logout *ChatStream_Logout `protobuf:"bytes,2,opt,name=logout,proto3,oneof"`
}

type ChatStream_Message_ struct {
	Message *ChatStream_Message `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

func (*ChatStream_Login_) isChatStream_Event() {}

func (*ChatStream_Logout_) isChatStream_Event() {}

func (*ChatStream_Message_) isChatStream_Event() {}

type ChatStream_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ChatStream_Login) Reset() {
	*x = ChatStream_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatStream_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStream_Login) ProtoMessage() {}

func (x *ChatStream_Login) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStream_Login.ProtoReflect.Descriptor instead.
func (*ChatStream_Login) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ChatStream_Login) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ChatStream_Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatStream_Logout) Reset() {
	*x = ChatStream_Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatStream_Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStream_Logout) ProtoMessage() {}

func (x *ChatStream_Logout) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStream_Logout.ProtoReflect.Descriptor instead.
func (*ChatStream_Logout) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{0, 1}
}

type ChatStream_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author  string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatStream_Message) Reset() {
	*x = ChatStream_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatStream_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStream_Message) ProtoMessage() {}

func (x *ChatStream_Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStream_Message.ProtoReflect.Descriptor instead.
func (*ChatStream_Message) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ChatStream_Message) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ChatStream_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_pb_chat_proto protoreflect.FileDescriptor

var file_pb_chat_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x9a, 0x02, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x2e, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x48, 0x00, 0x52,
	0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x23, 0x0a,
	0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x1a, 0x08, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x1a, 0x3b, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x32, 0x3a, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1e,
	0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6d, 0x69,
	0x30, 0x34, 0x31, 0x30, 0x2f, 0x63, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_chat_proto_rawDescOnce sync.Once
	file_pb_chat_proto_rawDescData = file_pb_chat_proto_rawDesc
)

func file_pb_chat_proto_rawDescGZIP() []byte {
	file_pb_chat_proto_rawDescOnce.Do(func() {
		file_pb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_chat_proto_rawDescData)
	})
	return file_pb_chat_proto_rawDescData
}

var file_pb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_chat_proto_goTypes = []interface{}{
	(*ChatStream)(nil),         // 0: chat.ChatStream
	(*ChatStream_Login)(nil),   // 1: chat.ChatStream.Login
	(*ChatStream_Logout)(nil),  // 2: chat.ChatStream.Logout
	(*ChatStream_Message)(nil), // 3: chat.ChatStream.Message
}
var file_pb_chat_proto_depIdxs = []int32{
	1, // 0: chat.ChatStream.login:type_name -> chat.ChatStream.Login
	2, // 1: chat.ChatStream.logout:type_name -> chat.ChatStream.Logout
	3, // 2: chat.ChatStream.message:type_name -> chat.ChatStream.Message
	0, // 3: chat.Chat.Stream:input_type -> chat.ChatStream
	0, // 4: chat.Chat.Stream:output_type -> chat.ChatStream
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_chat_proto_init() }
func file_pb_chat_proto_init() {
	if File_pb_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatStream_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatStream_Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatStream_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_chat_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ChatStream_Login_)(nil),
		(*ChatStream_Logout_)(nil),
		(*ChatStream_Message_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_chat_proto_goTypes,
		DependencyIndexes: file_pb_chat_proto_depIdxs,
		MessageInfos:      file_pb_chat_proto_msgTypes,
	}.Build()
	File_pb_chat_proto = out.File
	file_pb_chat_proto_rawDesc = nil
	file_pb_chat_proto_goTypes = nil
	file_pb_chat_proto_depIdxs = nil
}
